### ISSUE TITLE
Incompatibility with Matplotlib 3.3.0

### ISSUE THREAD

**Issue by jtprobst** [python-windrose/windrose#136]
We discovered a regression with the latest release of Matplotlib (version 3.3.0).

To reproduce:
```
$ pip3 install matplotlib windrose
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import windrose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jprobst/.local/lib/python3.6/site-packages/windrose/__init__.py", line 6, in <module>
    from .windrose import WindAxesFactory  # noqa
  File "/home/jprobst/.local/lib/python3.6/site-packages/windrose/windrose.py", line 762, in <module>
    @_autogen_docstring(WindroseAxes.contour)
  File "/home/jprobst/.local/lib/python3.6/site-packages/windrose/windrose.py", line 29, in _autogen_docstring
    addendum = docstring.Appender(msg, "\n\n")
AttributeError: module 'matplotlib.docstring' has no attribute 'Appender'
```

I reproduced this error on Ubuntu 18.04 LTS (Python 3.6.9 as seen above) and also with a vanilla Ubuntu 20.04 inside Docker (Python 3.8.2, matplotlib 3.3.0, windrose 1.6.7).

It can be seen [in the API changes document](https://matplotlib.org/3.3.0/api/api_changes.html) that `docstring.Appender` was removed without replacement.

Downgrading to `matplotlib==3.2.2` fixes the issue but shows the following warnings (tested with Ubuntu 20.04):
```
$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import windrose
/usr/local/lib/python3.8/dist-packages/windrose/windrose.py:29: MatplotlibDeprecationWarning: 
The Appender class was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  addendum = docstring.Appender(msg, "\n\n")
/usr/local/lib/python3.8/dist-packages/windrose/windrose.py:30: MatplotlibDeprecationWarning: 
The copy_dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use docstring.copy() and cbook.dedent() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
/usr/local/lib/python3.8/dist-packages/windrose/windrose.py:30: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.getdoc() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
/usr/local/lib/python3.8/dist-packages/windrose/windrose.py:30: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
```

**Comment by dancergraham** [comment]
Hi Johannes,

### Workaround

I think this has been fixed in the latest version on GitHub - I have tested under Python 3.8 with the latest matplotlib version from conda (3.2.2) and get no errors.  First remove your existing windrose installation then 
`pip install git+https://github.com/python-windrose/windrose`
to install

### Fix

This needs a new version to be pushed to pypi

**Comment by jtprobst** [comment]
Hi Graham,
thanks for your message! Very glad to hear that this is already fixed.
I saw that @scls19fr has been taking care of the releases so far. Maybe he could do one for us soon? This would be much appreciated! Merci d'avance.
Johannes

**Comment by weber-s** [comment]
Hello,

I should be fixed with the latest pypi version:

```
pip3 install windrose --upgrade
```
