### ISSUE TITLE
Windrose plottng error

### ISSUE THREAD

**Issue by saurabhsrvastav** [python-windrose/windrose#168]
Hi All, I am trying a series of Python windrose plots but for a certain loop, the windrose display error and doesn't plot anything although there is data in the array. Hereby, I am attaching the error and sample code. Both the array 'th' and 'L' have data without any 'nan' value.
Code: 
        

fig=plt.figure()
        ax = WindroseAxes.from_ax()    
        ax.bar(th, L)
        ax.set_legend()

Error:

posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
Traceback (most recent call last):

  File "C:\Users\admin\anaconda3\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\Users\admin\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 151, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2234, in print_figure
    bbox_inches = self.figure.get_tightbbox(

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\figure.py", line 1639, in get_tightbbox
    bbox = a.get_tightbbox(renderer)

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 4477, in get_tightbbox
    bbox = a.get_tightbbox(renderer)

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 306, in get_tightbbox
    bbox = self.get_window_extent(renderer)

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\patches.py", line 621, in get_window_extent
    return self.get_path().get_extents(self.get_transform())

  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\path.py", line 634, in get_extents
    xys = np.concatenate(xys)

  File "<__array_function__ internals>", line 5, in concatenate

ValueError: need at least one array to concatenate

<Figure size 640x640 with 1 Axes>

**Comment by ocefpaf** [comment]
> ax.bar(th, L)

We cannot debug this without  knowing that are `th` and `L`. Closing this but please feel free to re-open with a minimum dataset that reproduces your error.
