### ISSUE TITLE
Unable to install version 1.8.0 

### ISSUE THREAD

**Issue by winash12** [python-windrose/windrose#208]
When installing the latest version I get this error 

`/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 701, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python3/dist-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: module 'windrose' has no attribute '__version__'
`

**Comment by ZaamlamLeung** [comment]
try this code : conda install windrose

**Comment by ZaamlamLeung** [comment]
try this code : conda install windrose
